[tool.poetry]
name = "neurl-agric-background-service"
version = "0.1.0"
description = ""
authors = ["David Ibia <david.ibia@boxmarshall.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
